language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - "7.0"
  - "7.1"
  - "7.2"

install: composer install

script: echo "test"

jobs:
  include:
    - stage: inspect
      script: ./vendor/bin/phing inspect
      php: 7.0

stages:
  - inspect
  - test
