language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

before_install:
  - phpenv config-add travis/php.ini
  - composer self-update

install: composer install

script: ./vendor/bin/phing inspect

branches:
  only:
    - master
