language: php

php:
  - "7.0"
  - "7.1"
  - "7.2"

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

install:
    - ./bin/env.sh
    - composer install
    - ./vendor/bin/phing tests:db:create tests:config

script: ./vendor/bin/phing tests

jobs:
  include:
    - stage: inspect
      script: ./vendor/bin/phing inspect
      php: 7.0

stages:
  - inspect
  - test
